# This is a preferences file for the bacon tool
# More info at https://github.com/Canop/bacon


# Uncomment and change the value (true/false) to
# specify whether bacon should show a help line.
#
# help_line = false


# Exporting "locations" (by setting its 'auto' to true) lets you use
# them in an external tool, for example as a list of jump locations
# in an IDE or in a language server.
# (See https://dystroy.org/bacon/config/#export-locations),
#
# Possible line_format parts:
#  - kind: warning|error|test
#  - path: complete absolute path to the file
#  - line: 1-based line number
#  - column: 1-based column
#  - message: description of the item
#  - context: unstyled lines of output, separated with escaped newlines (`\\n`)
[exports.locations]
auto = true
exporter = "locations"
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"


# If you want some job to emit a beep on success or on failure,
# you need to globally enable sound, and you may set up the max volume here
# 
# With sound enabled, you may set up sound on a job with eg
#    on_success = "play-sound(name=90s-game-ui-6,volume=50)"
#    on_failure = "play-sound(name=beep-warning,volume=100)"
[sound]
enabled = true                                          # set true to allow sound
base_volume = "100%"                                    # global volume multiplier
on_success = "play-sound(name=90s-game-ui-6,volume=50)"
on_failure = "play-sound(name=beep-warning,volume=100)"

# Uncomment and change the key-bindings you want to define
# (some of those ones are the defaults and are just here for illustration)
[keybindings]
# esc = "back"
# g = "scroll-to-top"
# shift-g = "scroll-to-bottom"
# k = "scroll-lines(-1)"
# j = "scroll-lines(1)"
# ctrl-c = "quit"
# ctrl-q = "quit"
# q = "quit"
# F5 = "rerun"
# alt-s = "toggle-summary"
# alt-w = "toggle-wrap"
# alt-b = "toggle-backtrace"
# Home = "scroll-to-top"
# End = "scroll-to-bottom"
# Up = "scroll-lines(-1)"
# Down = "scroll-lines(1)"
# PageUp = "scroll-pages(-1)"
# PageDown = "scroll-pages(1)"
# Space = "scroll-pages(1)"
# a = "job:check-all"
# i = "job:initial"
# c = "job:clippy"
# c = "job:clippy-all"
# d = "job:doc-open"
# t = "job:test"
# r = "job:run"
# ctrl-e = "export:analysis"
# ctrl-c = "copy-unstyled-output"

# Catppuccin Mocha theme for Bacon
[skin]
# Status line - using base background with text foreground
status_fg = 205 # text (catppuccin mocha text - #cdd6f4)
status_bg = 235 # base (catppuccin mocha base - #1e1e2e)

# Key shortcuts - using mauve for emphasis
key_fg = 183        # mauve (#cba6f7)
status_key_fg = 183 # mauve (#cba6f7)

# Project name badge - using lavender on surface0
project_name_badge_fg = 183 # lavender (#b4befe)
project_name_badge_bg = 236 # surface0 (#313244)

# Job label badge - using base on mauve
job_label_badge_fg = 235 # base (#1e1e2e)
job_label_badge_bg = 183 # mauve (#cba6f7)

# Error badges - using base on red
errors_badge_fg = 235 # base (#1e1e2e)
errors_badge_bg = 203 # red (#f38ba8)

# Test fail badges - using base on peach
test_fails_badge_fg = 235 # base (#1e1e2e)
test_fails_badge_bg = 215 # peach (#fab387)

# Test pass badges - using base on green
test_pass_badge_fg = 235 # base (#1e1e2e)
test_pass_badge_bg = 151 # green (#a6e3a1)

# Warning badges - using base on yellow
warnings_badge_fg = 235 # base (#1e1e2e)
warnings_badge_bg = 227 # yellow (#f9e2af)

# Command error badges - using base on red
command_error_badge_fg = 235 # base (#1e1e2e)
command_error_badge_bg = 203 # red (#f38ba8)

# Change badges - using base on teal
change_badge_fg = 235 # base (#1e1e2e)
change_badge_bg = 152 # teal (#94e2d5)

# Computing stripe - using base on sky
computing_fg = 235 # base (#1e1e2e)
computing_bg = 117 # sky (#89dceb)

# Search highlighting - using peach
found_fg = 215               # peach (#fab387)
found_selected_bg = 215      # peach (#fab387)
search_input_prefix_fg = 215 # peach (#fab387)
search_summary_fg = 215      # peach (#fab387)

# Menu colors - using catppuccin surfaces
menu_border = 237           # surface1 (#45475a)
menu_bg = 235               # base (#1e1e2e)
menu_item_bg = 235          # base (#1e1e2e)
menu_item_selected_bg = 236 # surface0 (#313244)
menu_item_fg = 245          # subtext1 (#bac2de)
menu_item_selected_fg = 205 # text (#cdd6f4)
