tap "homebrew/bundle"
tap "homebrew/services"

# terminal
brew "ripgrep"
brew "luarocks"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "lazygit" # git
brew "wget"
brew "neovim" # editor
cask "ghostty" # terminal
brew "starship" # better prompt
brew "zoxide" # better cd
# brew "zellij" # terminal multiplexor - trying tmux next
brew "cloc" # count lines of code
# terminal - yazi
brew "ffmpeg" # video
brew "sevenzip" # view contents of zip
brew "jq" # json previewer
brew "poppler" # view pdf
brew "imagemagick" # other image preview
brew "xclip" # for clipboard
brew "yazi"

# fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
brew "ollama", restart_service: true
cask "font-meslo-lg-nerd-font"

# rust toolchain
brew "rustup"
brew "cargo-binstall"
brew "cargo-nextest"
brew "just"
brew "bacon"
# brew "bacon-ls" # not ready yet

# web
brew "node"
brew "pnpm"
brew "eslint"

#swift
brew "rbenv"
brew "fastlane"
brew "swiftformat"
brew "swiftlint"
brew "xcodegen"
brew "xcode-build-server"
cask "sf-symbols"

# macOS
tap "nikitabobko/tap"
cask "aerospace" # seeing if zellij works better with raycast driving
cask "slack"
cask "anki"
cask "raycast"
cask "leader-key"
cask "claude"
