# terminal
brew "ripgrep"
brew "luarocks"
brew "fd"
brew "fzf"
brew "gh"
cask "github"
brew "git"
brew "git-delta"
brew "lazygit" # git
brew "wget"
brew "neovim" # editor
cask "ghostty" # terminal
brew "starship" # better prompt
brew "zoxide" # better cd
brew "cloc" # count lines of code
brew "fswatch"
cask "balenaetcher"
# terminal - yazi
brew "ffmpeg" # video
brew "sevenzip" # view contents of zip
brew "jq" # json previewer
brew "poppler" # view pdf
brew "imagemagick" # other image preview
brew "xclip" # for clipboard
brew "yazi"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"

# fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
brew "ollama", restart_service: true
cask "font-meslo-lg-nerd-font"

# rust toolchain
brew "rustup"
brew "cargo-binstall"
brew "cargo-nextest"
brew "just"
brew "bacon"
# brew "bacon-ls" # not ready yet
brew "mdbook"
brew "lychee"

# cloud
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "tflint"
brew "doctl"
brew "kubernetes-cli"
brew "kustomize"
cask "pgadmin4"
brew "derailed/k9s/k9s"
cask "docker-desktop"
brew "sqlx-cli"
cask "postman"
cask "ngrok"
brew "stripe-cli"

# web
brew "node"
brew "pnpm"
brew "eslint"
tap "oven-sh/bun"
brew "bun"
brew "zola"

#swift
brew "rbenv"
brew "fastlane"
brew "swiftformat"
brew "swiftlint"
brew "xcodegen"
brew "xcode-build-server"
cask "sf-symbols"

# people
tap "hedge-ops/homebrew-tap"
cask "people-work"

# macOS
tap "nikitabobko/tap"
cask "aerospace" 
cask "anki"
cask "leader-key"

# AI
cask "claude"
brew "gemini-cli"

# Other editors
cask "visual-studio-code"
cask "spotify"
cask "zed"

# collaboration
cask "slack"
cask "google-chrome"
cask "discord"
